# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e9fe199a43e105a76b60541f76c7e4a73369911967b337a692bbf89a7aeb56c988ca23963cf50944056c8245a1e56297bd48301d928a1a89870506540637905

test:
  secret_key_base: b26340d5d295c5e89b062bcc3c36b661454c4f77a0acf952748a35465ec46a3df2048f0b8005bd51cab841aa07d9e12a9280943f0a23a2ba42dab4d5c022debb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
